---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "acme-client"
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - name: acme
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
    groups:
      - client
  - name: "acme-server"
    image: "ghcr.io/letsencrypt/pebble:latest"
    command: "-strict"
    networks:
      - name: acme
    ports:
      - "14000:14000"
      - "15000:15000"
    privileged: false
    pre_build_image: true
    groups:
      - server
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      client:
        acme_certificate_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_certificate_email: ci@nephelai.io
        acme_certificate_domain: "cloudflare-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}.nephelai.io"
        acme_certificate_cf_account_token: "{{ lookup('env', 'CF_ACCOUNT_TOKEN') }}"
        acme_certificate_cafile: /tmp/cafile
        acme_certificate_chainfile: /tmp/chainfile
        acme_certificate_file: /tmp/crtfile
        acme_certificate_keyfile: /tmp/keyfile
        acme_certificate_tempdir: /opt
        acme_certificate_validate_certs: false
