---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "acme-certificate-cloudflare-${MOLECULE_SCENARIO}"
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      all:
        acme_certificate_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_certificate_email: ci@nephelai.io
        acme_certificate_domain: "cloudflare-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}.nephelai.io"
        acme_certificate_cf_account_token: "{{ lookup('env', 'CF_ACCOUNT_TOKEN') }}"
        acme_certificate_cafile: /tmp/cafile
        acme_certificate_chainfile: /tmp/chainfile
        acme_certificate_file: /tmp/crtfile
        acme_certificate_keyfile: /tmp/keyfile
        acme_certificate_tempdir: /opt
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
