---
- name: Verify
  hosts: all
  vars:
    cert_dir: "/etc/letsencrypt"
    cert_file: "{{ cert_dir }}/live/{{ acme_certificate_domain }}.crt"
  tasks:
    - name: Query certificate issuer
      ansible.builtin.shell: "openssl x509 -in {{ cert_file }} -noout -text | grep Issuer:"
      register: _issuer_data
      changed_when: false

    - name: Verify certificate issuer
      ansible.builtin.assert:
        that: _issuer_name in _issuer_data.stdout
        fail_msg: "Certificate data is {{ _issuer_data.stdout }}"
        success_msg: "Certificate issuer is {{ _issuer_name }}"
      vars:
        _issuer_name: "Let's Encrypt"
