---
- name: Verify

  hosts: all

  vars:

    certdir: "/etc/letsencrypt"
    cacert: "{{ certdir }}/live/letsencrypt-stg-root-x1.pem"
    intcert: "{{ certdir }}/live/letsencrypt-stg-int-r3.pem"
    crtfile: "{{ certdir }}/live/{{ acme_certificate_domain }}.crt"
    keyfile: "{{ certdir }}/keys/id_rsa.{{ acme_certificate_domain }}"
    calink: "/tmp/cafile"
    keylink: "/tmp/keyfile"
    intlink: "/tmp/intfile"
    crtlink: "/tmp/crtfile"

  tasks:

    - name: test certificate chain
      ansible.builtin.command: "openssl verify -CAfile {{ cacert }} -untrusted {{ intcert }} {{ crtfile }}"

    - name: test certificate key
      ansible.builtin.command: "openssl rsa -in {{ keyfile }}"

    - name: test certificate chain symlinks
      ansible.builtin.command: "openssl verify -CAfile {{ calink }} -untrusted {{ intlink }} {{ crtlink }}"

    - name: test certificate key symlinks
      ansible.builtin.command: "openssl rsa -in {{ keylink }}"
