---
name: molecule

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

defaults:
  run:
    working-directory: "nephelaiio.acme_certificate_cloudflare"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "nephelaiio.acme_certificate_cloudflare"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: pip3 install poetry

      - name: Install pips
        run: poetry install

      - name: Lint code.
        run: |
          set -e
          poetry run yamllint --version
          poetry run yamllint .
          poetry run ansible-lint --version
          poetry run ansible-lint . -c .ansible-lint.yml

  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu2204
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10
          - rockylinux8
          - rockylinux9

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "nephelaiio.acme_certificate_cloudflare"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: pip3 install poetry

      - name: Install pips
        run: poetry install

      - name: Run Molecule tests.
        run: poetry run molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image }}
          CF_ACCOUNT_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
