---
name: molecule

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: "nephelaiio.acme_certificate_cloudflare"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu2204
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10
          - rockylinux8
          - rockylinux9

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: "nephelaiio.acme_certificate_cloudflare"

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Debug test environment
        run: make debug

      - name: Run molecule tests.
        run: make test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario.name }}
